export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const GET_COURSE_LIST = 'GET_COURSE_LIST'
export const UPDATE_CONTACT_FORM_FIELD = 'UPDATE_CONTACT_FORM_FIELD'